---
- hosts: homelab
  become: yes
  vars_files:
    - passwd.yml
  vars:
    ansible_become_pass: "{{ my_cluster_sudo_pass }}"

  pre_tasks:
  - name: Update cache
    apt:
      update_cache: yes
      cache_valid_time: 86400

  tasks:
  - name: Install sysstat
    apt:
      name:
        - sysstat
        - net-tools
        - iotop
        - bonnie++
        - speedtest-cli
        - iperf3
        - htop
        - smartmontools
        - neofetch
        - sysbench
        - p7zip-full
        - iptraf-ng
      state: present

  post_tasks:
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
