---
# equivalent to apt update && apt upgrade -y
# become sudo
# passwd.yml created using 'ansible-vault create passwd.yml'
# add something like this
#################################################################
# ---
# my_cluster_sudo_pass: super-strong-pass
#################################################################
# edit ansible.cfg and append variable...
##################################################################
# [homelab]
# ANSIBLE_VAULT_PASSWORD_FILE=/home/user/ansible/passwd.yml
##################################################################
# create inventory for the hosts

- hosts: homelab
  become: yes
  vars_files:
    - passwd.yml
  vars:
    ansible_become_pass: "{{ my_cluster_sudo_pass }}"
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

# Update docker images using scripts with docker run configs on docker server.
# Might update this so scripts are on ansible server. 
# Some use cases might prefer untouched scripts located on docker server,
# hence below. See example heimdal script in this repo.

- hosts: docker
  become: yes
  vars_files:
    - passwd.yml
  vars:
    ansible_become_pass: "{{ my_cluster_sudo_pass }}"
  tasks:
  - name: Update portainer
    command: ./portainer.sh # example script
    args:
      chdir: /home/user/scripts/
  - name: Update heimdal
    command: ./heimdall.sh # example script
    args:
      chdir: /home/user/scripts/
