---
# equivalent to apt update && apt upgrade -y
# become sudo
# passwd.yml created using 'ansible-vault create passwd.yml'
# add something like this
#################################################################
# ---
# my_cluster_sudo_pass: super-strong-pass
#################################################################
# edit ansible.cfg and append variable...
##################################################################
# [homelab]
# ANSIBLE_VAULT_PASSWORD_FILE=/home/user/ansible/passwd.yml
##################################################################
# create inventory for the hosts

- hosts: homelab
  become: yes
  vars_files:
    - passwd.yml
  vars:
    ansible_become_pass: "{{ my_cluster_sudo_pass }}"
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: dist 
      update_cache: yes
      cache_valid_time: 86400

# The below will copy scripts from the users scripts directory, to the docker server
# if the script doesn't exist, force=no.
# This step could be ommited, I understand leaving untouched scripts on the server
# could be disireable, but to update scripts use force=yes to overwrite the scripts on docker server.
# See example heimdal script in this repo.

- hosts: docker
  become: yes
  vars_files:
    - passwd.yml
  vars:
    ansible_become_pass: "{{ my_cluster_sudo_pass }}"
  tasks:
  - name: Copy Heimdall Script to Server
    copy:
      src: /home/user/scripts/heimdall.sh
      dest: /home/user/scripts/
      force: no
      owner: user
      group: user
      mode: u=rwx,g=r,o=r
  - name: Copy Portainer Script to Server
    copy:
      src: /home/user/scripts/portainer.sh
      dest: /home/user/scripts/
      force: no
      owner: user
      group: user
      mode: u=rwx,g=r,o=r

# Update docker images using scripts with docker run configs on docker server.

- hosts: docker
  become: yes
  vars_files:
    - passwd.yml
  vars:
    ansible_become_pass: "{{ my_cluster_sudo_pass }}"
  tasks:
  - name: Update portainer
    command: ./portainer.sh # example script
    args:
      chdir: /home/user/scripts/
  - name: Update heimdal
    command: ./heimdall.sh # example script
    args:
      chdir: /home/user/scripts/
